name: Close stalled issues and PRs
on:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@f94f76c8fa2c48bb2982a099c29a0caadb92917e  # v0.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            {
                "stalled": {
                    "remove_label_on_close": false,
                    "remove_label_on_comment": false,
                    "delay": 2592000,
                    "message": "Closing this because it has stalled. Feel free to reopen if this issue/PR is still relevant, or to ping the collaborator who labelled it stalled if you have any questions."
                }
            }
