name: Close stale pull requests
on:
  schedule:
    # Run every day at 1:00 AM UTC.
    - cron: 0 1 * * *

# yamllint disable rule:empty-lines
env:
  CLOSE_MESSAGE: >
    This pull request has had no updates in the past 6 months.
    We appreciate your contribution, but due to the lack of
    recent activity, we're closing it for now. If you believe this
    decision should be reconsidered, please feel free to leave a comment.

  WARN_MESSAGE: >
    This pull request has had no updates in the last 5 months. We value your
    contribution, but since there hasn't been any recent progress, it is being
    marked as stale and will be closed if there is no activity in the next month.
    If you believe this decision is not appropriate, please leave a comment
    on the pull request.
# yamllint enable

permissions:
  contents: read

jobs:
  stale:
    permissions:
      pull-requests: write  # for actions/stale to close stale PRs
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e  # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          end-date: ${{ env.END_DATE }}
          days-before-issue-stale: -1
          days-before-issue-close: -1
          days-before-stale: 150
          days-before-close: 30
          stale-issue-label: stale
          close-issue-message: ${{ env.CLOSE_MESSAGE }}
          stale-issue-message: ${{ env.WARN_MESSAGE }}
          exempt-pr-labels: never-stale
          # max requests it will send per run to the GitHub API before it deliberately exits to avoid hitting API rate limits
          operations-per-run: 500
          remove-stale-when-updated: true
